-- CREATE DATABASE IF NOT EXISTS webquiz;
-- USE webquiz;

-- CREATE TABLE IF NOT EXISTS questions (
--     id INT AUTO_INCREMENT PRIMARY KEY,
--     question_text VARCHAR(255) NOT NULL,
--     option1 VARCHAR(255) NOT NULL,
--     option2 VARCHAR(255) NOT NULL,
--     option3 VARCHAR(255) NOT NULL,
--     option4 VARCHAR(255) NOT NULL
-- );
